### ISSUE TITLE
Download Seite 

### ISSUE THREAD

**Issue by ajaguar** [efg-ludwigshafen/efg-ludwigshafen.github.io#35]
Mitarbeiterseite zum Download von Vorlagen. Kann ruhig öffentlich sein. Liste von Vorlagen mit Download Link von owncloud.

**Comment by dominikschreiber** [comment]
könnte man "pressepaket" oder so nennen

**Comment by dominikschreiber** [comment]
fixed w/ commit ece1cf3e2afa8b2016fa7cd652841f4b4437e468
