### ISSUE TITLE
calendar is not working anymore

### ISSUE THREAD

**Issue by ajaguar** [efg-ludwigshafen/efg-ludwigshafen.github.io#45]
maybe only on safari -_-
<img width="921" alt="bildschirmfoto 2017-02-21 um 19 38 34" src="https://cloud.githubusercontent.com/assets/4869304/23179257/85452792-f86d-11e6-8586-8579c952f7d1.PNG">

**Comment by dominikschreiber** [comment]
seems to be related to https://github.com/angular-ui/ui-calendar/issues/418#issuecomment-233990021
